### PR TITLE
Source dataset from Blue Brain Nexus store

### PR DESCRIPTION
**Pull request by MFSY**
Source dataset from Blue Brain Nexus store in Glucose is a risk factor for COVID-19 (3000 papers) notebook

### CODE REVIEW

**Review by eugeniashurko — COMMENTED** [review]
Maybe we should also remove the source data files then, to make the repo more light

**Comment by eugeniashurko** [comment]
Hi! I would also clean the outputs of the notebook, for me they always create conflicts that are annoying to solve

**Comment by MFSY** [comment]
Sure. Done.

**Comment by eugeniashurko** [comment]
Hi! Well spotted the files! Actually i didn't mean this files, but the outputs of the glucose notebook cells.

**Review by eugeniashurko — APPROVED** [review]

**Comment by MFSY** [comment]
> Hi! Well spotted the files! Actually i didn't mean this files, but the outputs of the glucose notebook cells.

I see. I think the notebook outputs are now removed

**Pull request merged**
